DjangoTests/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = patterns('',
    url(r'^$', 'DjangoTests.views.home', name='home'),
    url(r'test.html', 'DjangoTests.views.test', name='test'),
    url(r'^drive/', include('drive.urls', namespace='drive')),
    url(r'^box/', include('box.urls', namespace='box')),
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += staticfiles_urlpatterns()

box/urls.py
from django.conf.urls import patterns, url

from box import views


hex_digit = r'[0-9a-fA-F]'
mac_address = hex_digit * 2 * 6

urlpatterns = patterns('',
                       url(r'(?P<mac>' + mac_address + r')/' +
                           r'report_event',
                           views.report_event, name='report_event'),
                       url(r'(?P<mac>' + mac_address + r')/' +
                           r'get/' +
                           r'allowances.(?P<fmt>[^/]+)',
                           views.get_allowance, name='get_allowance'),
                       )

drive/urls.py
from django.conf.urls import patterns, url

from drive import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^login/$', views.user_login, name='login'),
                       url(r'^register/$', views.register, name='register'),
                       url(r'^logout/$', views.user_logout, name='logout'),
                       url(r'^household/$', views.household, name='household'),
                       url(r'^household/join_reply/$', views.join_reply, name='join_reply'),
                       url(r'^household/join_request/$', views.join_request, name='join_request'),
                       url(r'^household/box_join/$', views.box_join, name='box_join'),
                       url(r'^household/box_control/$', views.box_control, name='box_control'),
                       )

drive/models.py
from django.db import models
from django.contrib.auth.models import User as AuthUser
from box.models import DriveBox


class Household(models.Model):
    name = models.CharField(max_length=32, unique=True)
    boxes = models.ManyToManyField(DriveBox, through='HouseholdBoxes', blank=True)

    def __unicode__(self):
        return self.name


class ScreenLockUser(models.Model):
    user = models.OneToOneField(AuthUser)
    household = models.ForeignKey(Household, null=True, db_index=True, blank=True)
    nickname = models.CharField(max_length=32)
    caretaker = models.BooleanField(default=False)
    credits = models.IntegerField(default=0)

    _join_request = models.ForeignKey(Household, null=True, blank=True, related_name='join_request_set')

    def __unicode__(self):
        return u'{0}{1}'.format(self.nickname, u'+' if self.caretaker else u'')

    def has_household(self):
        return self.household is not None

    def has_join_request(self):
        return self._join_request is not None


class HouseholdBoxes(models.Model):
    household = models.ForeignKey(Household)
    box = models.ForeignKey(DriveBox, unique=True)
    alias = models.CharField(max_length=32)

    class Meta:
        unique_together = (('household', 'alias'),)

    def __unicode__(self):
        return self.alias


class ChoreStates:
    def __init__(self):
        pass

    incomplete = 0
    pending_approval = 1
    done = 2


class Chores(models.Model):
    user = models.ForeignKey(ScreenLockUser)
    name = models.CharField(max_length=32)
    state = models.IntegerField(default=ChoreStates.incomplete)
    date = models.DateField()
    credits = models.IntegerField(default=1)

    def __unicode__(self):
        return self.name


class Rewards(models.Model):
    name = models.CharField(max_length=32)
    household = models.ForeignKey(Household)
    credits = models.IntegerField(default=1)

    def __unicode__(self):
        return self.name

drive/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User as authUser
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext

from models import ScreenLockUser, Household, HouseholdBoxes
from box.models import DriveBox

from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST


@login_required
def index(request):
    screen_lock_user = ScreenLockUser.objects.get(user=request.user)
    context = RequestContext(request)
    return render_to_response('drive/index.html',
                              {
                                  'screen_lock_user': screen_lock_user,
                                  'home': True
                              },
                              context)


@login_required
def household(request):
    context = RequestContext(request)
    screen_lock_user = get_object_or_404(ScreenLockUser, user=request.user)
    additional_context = {'screen_lock_user': screen_lock_user}

    if screen_lock_user.has_household():
        additional_context.update({'caretakers': screen_lock_user.household.screenlockuser_set.filter(caretaker=True),
                                   'children': screen_lock_user.household.screenlockuser_set.filter(caretaker=False),
                                   'boxes': screen_lock_user.household.householdboxes_set.filter(),
                                   'household': True,
                                   })

        if screen_lock_user.caretaker:
            additional_context.update(
                {'join_requests': screen_lock_user.household.join_request_set.filter()})

        return render_to_response('drive/household.html',
                                  additional_context,
                                  context)
    elif screen_lock_user.has_join_request():
        additional_context.update(
            {'join_request_household': screen_lock_user._join_request})

        return render_to_response('drive/active_join_request.html',
                                  additional_context,
                                  context)
    else:
        return render_to_response('drive/no_household.html',
                                  additional_context,
                                  context)


@login_required
@require_POST
def join_request(request):
    context = RequestContext(request)
    screen_lock_user = get_object_or_404(ScreenLockUser, user=request.user)
    action = request.POST['action']
    household_name = request.POST['household']

    if action == 'create':
        if len(Household.objects.filter(name=household_name)) == 0:
            household = Household(name=household_name)
            household.save()
            screen_lock_user.household = household
            screen_lock_user.caretaker = True
        else:
            return HttpResponse('Household already exists')
    elif action == 'join':
        screen_lock_user._join_request = get_object_or_404(Household, name=household_name)

    screen_lock_user.save()

    return HttpResponseRedirect(reverse('drive:household'))


@login_required
@require_POST
def join_reply(request):
    screen_lock_user = ScreenLockUser.objects.get(user=request.user)
    household = screen_lock_user.household

    requesting_user = household.join_request_set.get(pk=request.POST['requesting_user_pk'])
    if request.POST['action'] == u'accept':
        requesting_user.household = household
        requesting_user._join_request = None
        requesting_user.caretaker = False
    elif request.POST['action'] == u'reject':
        requesting_user._join_request = None
    requesting_user.save()

    return HttpResponseRedirect(reverse('drive:household'))


def box_join(request):
    box = get_object_or_404(DriveBox, mac=request.GET['mac'])
    if len(HouseholdBoxes.objects.filter(box=box)) > 0:
        return HttpResponse(status=409)

    user = get_object_or_404(ScreenLockUser, user__email=request.GET['user_email'])
    hb = HouseholdBoxes(household=user.household, box=box, alias=box.mac)
    hb.save()
    return HttpResponse()


@login_required
@require_POST
def box_control(request):
    screen_lock_user = ScreenLockUser.objects.get(user=request.user)
    box = screen_lock_user.household.householdboxes_set.get(box__mac=request.POST['box']).box

    action = request.POST['action']

    box.control = action == 'enable'
    box.save()
    return HttpResponseRedirect(reverse('drive:household'))


def register(request):
    context = RequestContext(request)

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        password_ver = request.POST['password_ver']
        nickname = request.POST['nickname']
        email = request.POST['email']

        if password != password_ver:
            return HttpResponse("Password mismatch!")

        try:
            authUser.objects.get(username=username)
            return HttpResponse("Can't register user, try a different username.")
        except authUser.DoesNotExist:
            pass  # Good, we can create your username.

        new_auth_user = authUser(username=username, email=email)
        new_auth_user.set_password(raw_password=password)
        new_auth_user.save()

        user = ScreenLockUser(user=new_auth_user, nickname=nickname)
        user.save()

        user = authenticate(username=username, password=password)

        if user:
            login(request, user)
            return HttpResponseRedirect(reverse('drive:index'))
        else:
            return HttpResponse("Can't register user, unknown error.")

    # The request is not a HTTP POST, so display the registration form.
    # This scenario would most likely be a HTTP GET.
    else:
        # No context variables to pass to the template system, hence the
        # blank dictionary object...
        return render_to_response('drive/register.html', {'register': True}, context)


def user_login(request):
    context = RequestContext(request)

    next = ''

    if request.GET:
        next = request.GET['next']

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                if next == '':
                    return HttpResponseRedirect(reverse('drive:index'))
                else:
                    return HttpResponseRedirect(next)
            else:
                return HttpResponse("Your Drive account is disabled.")
        else:
            return HttpResponse("Invalid login details supplied.")

    # The request is not a HTTP POST, so display the login form.
    # This scenario would most likely be a HTTP GET.
    else:
        # No context variables to pass to the template system, hence the
        # blank dictionary object...
        return render_to_response('drive/login.html',
                                  {
                                      'next': next,
                                      'login': True
                                  },
                                  context)


def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('drive:index'))

templates/drive/active_join_request.html
{% extends 'drive/base.html' %}

{% block title %}
    household
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <h1>A join request to <strong>{{ join_request_household.name }}</strong> is pending a reply from a caretaker.</h1>
        </div>
    </div>
{% endblock %}

templates/drive/base.html
{% extends 'drive/bootstrap.html' %}

{% load url from future %}

{% load bootstrap3 %}

{% block bootstrap3_content %}
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">ScreenLock</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li{% if home %} class="active" {% endif %}><a href="{% url 'home' %}">Home</a></li>
                    <li{% if household %} class="active" {% endif %}><a href="{% url 'drive:household' %}">Household</a></li>
                </ul>
                {% if user and user.is_authenticated %}
                    <ul class="nav navbar-nav navbar-right">
                        <li><p class="navbar-text">{{ screen_lock_user.nickname }}</p></li>
                        <li><a href="{% url 'drive:logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
                    </ul>
                {% else %}
                    <ul class="nav navbar-nav navbar-right">
                        <li{% if register %} class="active"{% endif %}><a href="{% url 'drive:register' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                        <li{% if login %} class="active"{% endif %}><a href="{% url 'drive:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                    </ul>
                {% endif %}
            </div>
        </div>
    </nav>
    <div class="container-fluid">
        {% bootstrap_messages %}

        {% block content %}(no content){% endblock %}
    </div>

{% endblock %}

templates/drive/bootstrap.html
{% extends 'bootstrap3/bootstrap3.html' %}

{% block bootstrap3_title %}ScreenLock {% block title %}{% endblock %}{% endblock %}

templates/drive/household.html
{% extends 'drive/base.html' %}

{% block title %}
    household
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-sm-12">
            <h1>{{ screen_lock_user.household.name }}</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <h2>Caretakers <small><span class="badge">{{ caretakers|length }}</span></small></h2>
            <table class="table">
                <thead>
                    <th>Nickname</th>
                    <th>Email</th>
                    <!--{% if screen_lock_user.caretaker %}
                        <th>Actions</th>
                    {% endif %}-->
                </thead>
                {% for c in caretakers %}
                    <tr{% ifequal c.nickname screen_lock_user.nickname %} class="success"{% endifequal %}>
                        <td>{{ c.nickname }}</td>
                        <td>{{ c.user.email}}</td>
                        <!--{% if screen_lock_user.caretaker %}
                            <td class="warning">
                                TBD
                            </td>
                        {% endif %}-->
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <h2>Children <small><span class="badge">{{ children|length }}</span></small></h2>
            {% if children|length %}
                <table class="table">
                    <thead>
                        <th>Nickname</th>
                        <th>Email</th>
                        <th>Credits</th>
                        <!--{% if screen_lock_user.caretaker %}
                            <th>Actions</th>
                        {% endif %}-->
                    </thead>
                    {% for c in children %}
                        <tr{% ifequal c.nickname screen_lock_user.nickname %} class="success"{% endifequal %}>
                            <td>{{ c.nickname }}</td>
                            <td>{{ c.user.email }}</td>
                            <td>{{ c.credits }}</td>
                            <!--{% if screen_lock_user.caretaker %}
                                <td class="warning">
                                    TBD
                                </td>
                            {% endif %}-->
                        </tr>
                    {% endfor %}
                </table>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <h2>Boxes <small><span class="badge">{{ boxes|length }}</span></small></h2>
            {% if boxes|length %}
                <table class="table">
                    <thead>
                        <th>MAC</th>
                        <th>Alias</th>
                        <th>Status</th>
                        <th>Control</th>
                    </thead>
                    {% for b in boxes %}
                        <tr>
                            <td>{{ b.box.mac }}</td>
                            <td>{{ b.alias }}</td>
                            <td>
                                <div class="btn-group">
                                    <button disabled class="btn {% if b.box.status %} btn-success {% endif %}">Active <span class="glyphicon glyphicon-ok-sign"></span></button>
                                    <button disabled class="btn {% if not b.box.status %} btn-danger {% endif %}">Inactive <span class="glyphicon glyphicon-remove-sign"></span></button>
                                </div>
                            </td>
                            <td>
                                {% if screen_lock_user.caretaker %}
                                <form method="post" action="{% url 'drive:box_control' %}">
                                    {% csrf_token %}
                                    <div class="btn-group">
                                        <button type="submit" name="action" value="enable" class="btn {% if b.box.control %} btn-success {% endif %}">Enable <span class="glyphicon glyphicon-ok-sign"></span></button>
                                        <button type="submit" name="action" value="disable" class="btn {% if not b.box.control %} btn-danger {% endif %}">Disable <span class="glyphicon glyphicon-remove-sign"></span></button>
                                    </div>
                                    <input type="hidden" name="box" value="{{ b.box.mac }}"/>
                                </form>
                                {% else %}
                                    <div class="btn-group">
                                        <button disabled class="btn {% if b.box.control %} btn-success {% endif %}">Enable <span class="glyphicon glyphicon-ok-sign"></span></button>
                                        <button disabled class="btn {% if not b.box.control %} btn-danger {% endif %}">Disable <span class="glyphicon glyphicon-remove-sign"></span></button>
                                    </div>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            {% endif %}
        </div>
    </div>
    {% if screen_lock_user.caretaker %}
        <div class="row">
            <div class="col-sm-12">
                <h2>Join requests <small><span class="badge">{{ join_requests|length }}</span></small></h2>
                {% if join_requests|length %}
                    <table class="table">
                        <thead>
                            <th>Nickname</th>
                            <th>email</th>
                            <th>Caretaker/Child</th>
                            <th>Action</th>
                        </thead>
                        {% for r in join_requests %}
                            <tr>
                                <td>{{ r.nickname }}</td>
                                <td>{{ r.user.email }}</td>
                                <td>{% if r.caretaker %}Caretaker{% else %}Child{% endif %}</td>
                                <td>
                                    <form method="post" action="{% url 'drive:join_reply' %}">
                                        {% csrf_token %}
                                        <div class="btn-group">
                                            <button type="submit" name="action" value="accept" class="btn btn-success">Accept <span class="glyphicon glyphicon-ok"></span></button>
                                            <button type="submit" name="action" value="reject" class="btn btn-danger">Reject <span class="glyphicon glyphicon-remove"></span></button>
                                        </div>
                                        <input type="hidden" name="requesting_user_pk" value="{{ r.pk }}"/>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                {% endif %}
            </div>
        </div>
    {% endif %}
{% endblock %}

templates/drive/index.html
{% extends 'drive/base.html' %}

{% block title %}
    home
{% endblock %}

{% block content %}

    {% if user and user.is_authenticated %}
        <div class="jumbotron">
            <h1>ScreenLock user overview</h1>
            <p>Contents TBD...</p>
        </div>
    {% endif %}

{% endblock %}

templates/drive/login.html
{% extends 'drive/base.html' %}

{% block title %}
    login
{% endblock %}

{% block content %}

    <form id="login_form" method="post" action={% url 'drive:login' %}?next={{ next }}>
        {% csrf_token %}
        Username: <input type="text" name="username" value="" size="50" />
        <br />
        Password: <input type="password" name="password" value="" size="50" />
        <br />

        <input type="submit" value="submit" />
    </form>

{% endblock %}

templates/drive/no_household.html
{% extends 'drive/base.html' %}

{% block title %}
    household
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <h1>Your account isn't associated with a household.</h1>
            <form method="post" action="{% url 'drive:join_request' %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="household">Household name:</label>
                    <input name="household" type="text" class="form-control" id="household"/>
                </div>
                <button type="submit" name="action" value="join" class="btn btn-default">Join</button>
                <button type="submit" name="action" value="create" class="btn btn-default">Create</button>
            </form>

        </div>
    </div>

{% endblock %}

templates/drive/register.html
{% extends 'drive/base.html' %}

{% block title %}
    register
{% endblock %}

{% block content %}

    <h1>Register with Drive</h1>
    <form id="user_form" method="post" action={% url 'drive:register' %}
            enctype="multipart/form-data">

        {% csrf_token %}

        Username: <input type="text" name="username" value="" size="50" />
        <br />
        Password: <input type="password" name="password" value="" size="50" />
        <br />
        Password verification: <input type="password" name="password_ver" value="" size="50" />
        <br />
        Email: <input type="email" name="email" value="" />
        <br />
        Nickname: <input type="text" name="nickname" value="" />
        <br />


        <input type="submit" name="submit" value="Register" />
    </form>

{% endblock %}